// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MagentoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void magento() {
    driver.get("https://magento.softwaretestingboard.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.linkText("Sign In")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("shashi@gmail.com");
    driver.findElement(By.id("pass")).sendKeys("shashi@2016");
    driver.findElement(By.id("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".header:nth-child(2) > .customer-welcome .action")).click();
    driver.findElement(By.linkText("Sign Out")).click();
    driver.close();
  }
}
